"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.revenue_modeler_controller_api import RevenueModelerControllerApi  # noqa: E501


class TestRevenueModelerControllerApi(unittest.TestCase):
    """RevenueModelerControllerApi unit test stubs"""

    def setUp(self):
        self.api = RevenueModelerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_revenue_model(self):
        """Test case for delete_revenue_model

        """
        pass

    def test_get_revenue_model(self):
        """Test case for get_revenue_model

        """
        pass

    def test_model_revenue(self):
        """Test case for model_revenue

        """
        pass

    def test_save_revenue_model(self):
        """Test case for save_revenue_model

        """
        pass


if __name__ == '__main__':
    unittest.main()
