"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fact_auto_filler_controller_api import FactAutoFillerControllerApi  # noqa: E501


class TestFactAutoFillerControllerApi(unittest.TestCase):
    """FactAutoFillerControllerApi unit test stubs"""

    def setUp(self):
        self.api = FactAutoFillerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fixed_cost_auto_fills(self):
        """Test case for get_fixed_cost_auto_fills

        """
        pass

    def test_get_percent_of_revenue_auto_fills(self):
        """Test case for get_percent_of_revenue_auto_fills

        """
        pass


if __name__ == '__main__':
    unittest.main()
