"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mx_parser_evaluate_response import MxParserEvaluateResponse


class TestMxParserEvaluateResponse(unittest.TestCase):
    """MxParserEvaluateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMxParserEvaluateResponse(self):
        """Test MxParserEvaluateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MxParserEvaluateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
