"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cell import Cell
from openapi_client.model.derived_stock_analytics import DerivedStockAnalytics
from openapi_client.model.model import Model
globals()['Cell'] = Cell
globals()['DerivedStockAnalytics'] = DerivedStockAnalytics
globals()['Model'] = Model
from openapi_client.model.stock_analysis2 import StockAnalysis2


class TestStockAnalysis2(unittest.TestCase):
    """StockAnalysis2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStockAnalysis2(self):
        """Test StockAnalysis2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StockAnalysis2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
