"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.discrete import Discrete


class TestDiscrete(unittest.TestCase):
    """Discrete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiscrete(self):
        """Test Discrete"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Discrete()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
