"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.model_builder_factory_controller_api import ModelBuilderFactoryControllerApi  # noqa: E501


class TestModelBuilderFactoryControllerApi(unittest.TestCase):
    """ModelBuilderFactoryControllerApi unit test stubs"""

    def setUp(self):
        self.api = ModelBuilderFactoryControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_best_effort_model(self):
        """Test case for best_effort_model

        """
        pass


if __name__ == '__main__':
    unittest.main()
