"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.percent_of_revenue import PercentOfRevenue


class TestPercentOfRevenue(unittest.TestCase):
    """PercentOfRevenue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPercentOfRevenue(self):
        """Test PercentOfRevenue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PercentOfRevenue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
