"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.mx_parser_controller_api import MxParserControllerApi  # noqa: E501


class TestMxParserControllerApi(unittest.TestCase):
    """MxParserControllerApi unit test stubs"""

    def setUp(self):
        self.api = MxParserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_evaluate1(self):
        """Test case for evaluate1

        """
        pass


if __name__ == '__main__':
    unittest.main()
