"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.zacks_estimates_controller_api import ZacksEstimatesControllerApi  # noqa: E501


class TestZacksEstimatesControllerApi(unittest.TestCase):
    """ZacksEstimatesControllerApi unit test stubs"""

    def setUp(self):
        self.api = ZacksEstimatesControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_revenue_projections(self):
        """Test case for revenue_projections

        """
        pass


if __name__ == '__main__':
    unittest.main()
