"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.published_stock_analysis_controller_api import PublishedStockAnalysisControllerApi  # noqa: E501


class TestPublishedStockAnalysisControllerApi(unittest.TestCase):
    """PublishedStockAnalysisControllerApi unit test stubs"""

    def setUp(self):
        self.api = PublishedStockAnalysisControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_published_stock_analyses(self):
        """Test case for find_published_stock_analyses

        """
        pass

    def test_get_published_stock_analysis(self):
        """Test case for get_published_stock_analysis

        """
        pass


if __name__ == '__main__':
    unittest.main()
