"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.filing_entity_manager_unsecured_controller_api import FilingEntityManagerUnsecuredControllerApi  # noqa: E501


class TestFilingEntityManagerUnsecuredControllerApi(unittest.TestCase):
    """FilingEntityManagerUnsecuredControllerApi unit test stubs"""

    def setUp(self):
        self.api = FilingEntityManagerUnsecuredControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_filing_entity(self):
        """Test case for get_filing_entity

        """
        pass


if __name__ == '__main__':
    unittest.main()
