"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.edgar_filing_metadata import EdgarFilingMetadata


class TestEdgarFilingMetadata(unittest.TestCase):
    """EdgarFilingMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgarFilingMetadata(self):
        """Test EdgarFilingMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgarFilingMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
