"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.fixed_cost import FixedCost


class TestFixedCost(unittest.TestCase):
    """FixedCost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFixedCost(self):
        """Test FixedCost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FixedCost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
