"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.component import Component


class TestComponent(unittest.TestCase):
    """Component unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponent(self):
        """Test Component"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Component()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
