"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.commentary import Commentary
from openapi_client.model.compounded_growth import CompoundedGrowth
from openapi_client.model.discrete import Discrete
from openapi_client.model.fixed_cost import FixedCost
from openapi_client.model.historical_value import HistoricalValue
from openapi_client.model.percent_of_revenue import PercentOfRevenue
from openapi_client.model.percent_of_total_asset import PercentOfTotalAsset
from openapi_client.model.subscription_revenue import SubscriptionRevenue
from openapi_client.model.sum_of_other_items import SumOfOtherItems
from openapi_client.model.unit_sales_revenue import UnitSalesRevenue
globals()['Commentary'] = Commentary
globals()['CompoundedGrowth'] = CompoundedGrowth
globals()['Discrete'] = Discrete
globals()['FixedCost'] = FixedCost
globals()['HistoricalValue'] = HistoricalValue
globals()['PercentOfRevenue'] = PercentOfRevenue
globals()['PercentOfTotalAsset'] = PercentOfTotalAsset
globals()['SubscriptionRevenue'] = SubscriptionRevenue
globals()['SumOfOtherItems'] = SumOfOtherItems
globals()['UnitSalesRevenue'] = UnitSalesRevenue
from openapi_client.model.item import Item


class TestItem(unittest.TestCase):
    """Item unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItem(self):
        """Test Item"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Item()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
