"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.unit_sales_revenue import UnitSalesRevenue


class TestUnitSalesRevenue(unittest.TestCase):
    """UnitSalesRevenue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitSalesRevenue(self):
        """Test UnitSalesRevenue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnitSalesRevenue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
