"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.filing_entity_manager_controller_api import FilingEntityManagerControllerApi  # noqa: E501


class TestFilingEntityManagerControllerApi(unittest.TestCase):
    """FilingEntityManagerControllerApi unit test stubs"""

    def setUp(self):
        self.api = FilingEntityManagerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bootstrap_filing_entity(self):
        """Test case for bootstrap_filing_entity

        """
        pass

    def test_bootstrap_filing_entity_sync(self):
        """Test case for bootstrap_filing_entity_sync

        """
        pass

    def test_create_filing_entity(self):
        """Test case for create_filing_entity

        """
        pass

    def test_save_filing_entity(self):
        """Test case for save_filing_entity

        """
        pass


if __name__ == '__main__':
    unittest.main()
