"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.revenue_model import RevenueModel


class TestRevenueModel(unittest.TestCase):
    """RevenueModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRevenueModel(self):
        """Test RevenueModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RevenueModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
