"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.marketing_controller_api import MarketingControllerApi  # noqa: E501


class TestMarketingControllerApi(unittest.TestCase):
    """MarketingControllerApi unit test stubs"""

    def setUp(self):
        self.api = MarketingControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_early_access_requests(self):
        """Test case for early_access_requests

        """
        pass

    def test_feedback20210329(self):
        """Test case for feedback20210329

        """
        pass

    def test_stock_analysis_interest(self):
        """Test case for stock_analysis_interest

        """
        pass

    def test_stock_analysis_request(self):
        """Test case for stock_analysis_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
