"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.address import Address
from openapi_client.model.model_template import ModelTemplate
globals()['Address'] = Address
globals()['ModelTemplate'] = ModelTemplate
from openapi_client.model.filing_entity import FilingEntity


class TestFilingEntity(unittest.TestCase):
    """FilingEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilingEntity(self):
        """Test FilingEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilingEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
