"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.edgar_explorer_controller_api import EdgarExplorerControllerApi  # noqa: E501


class TestEdgarExplorerControllerApi(unittest.TestCase):
    """EdgarExplorerControllerApi unit test stubs"""

    def setUp(self):
        self.api = EdgarExplorerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_entities(self):
        """Test case for search_entities

        """
        pass

    def test_search_filings(self):
        """Test case for search_filings

        """
        pass


if __name__ == '__main__':
    unittest.main()
