"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.tag_controller_api import TagControllerApi  # noqa: E501


class TestTagControllerApi(unittest.TestCase):
    """TagControllerApi unit test stubs"""

    def setUp(self):
        self.api = TagControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        """
        pass

    def test_find_tag(self):
        """Test case for find_tag

        """
        pass

    def test_save_tag(self):
        """Test case for save_tag

        """
        pass


if __name__ == '__main__':
    unittest.main()
