"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.stock_analysis_workflow_download_controller_api import StockAnalysisWorkflowDownloadControllerApi  # noqa: E501


class TestStockAnalysisWorkflowDownloadControllerApi(unittest.TestCase):
    """StockAnalysisWorkflowDownloadControllerApi unit test stubs"""

    def setUp(self):
        self.api = StockAnalysisWorkflowDownloadControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download(self):
        """Test case for download

        """
        pass


if __name__ == '__main__':
    unittest.main()
