"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mx_parser_evaluate_request import MxParserEvaluateRequest


class TestMxParserEvaluateRequest(unittest.TestCase):
    """MxParserEvaluateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMxParserEvaluateRequest(self):
        """Test MxParserEvaluateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MxParserEvaluateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
