"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.address import Address
from openapi_client.model.item import Item
globals()['Address'] = Address
globals()['Item'] = Item
from openapi_client.model.cell import Cell


class TestCell(unittest.TestCase):
    """Cell unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCell(self):
        """Test Cell"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Cell()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
