"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.early_access_request import EarlyAccessRequest


class TestEarlyAccessRequest(unittest.TestCase):
    """EarlyAccessRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEarlyAccessRequest(self):
        """Test EarlyAccessRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EarlyAccessRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
