"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.percent_of_another_item import PercentOfAnotherItem


class TestPercentOfAnotherItem(unittest.TestCase):
    """PercentOfAnotherItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPercentOfAnotherItem(self):
        """Test PercentOfAnotherItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PercentOfAnotherItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
