"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.orphaned_items_finder_controller_api import OrphanedItemsFinderControllerApi  # noqa: E501


class TestOrphanedItemsFinderControllerApi(unittest.TestCase):
    """OrphanedItemsFinderControllerApi unit test stubs"""

    def setUp(self):
        self.api = OrphanedItemsFinderControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orphaned_items(self):
        """Test case for orphaned_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
