"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cell import Cell
globals()['Cell'] = Cell
from openapi_client.model.waterfall import Waterfall


class TestWaterfall(unittest.TestCase):
    """Waterfall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterfall(self):
        """Test Waterfall"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Waterfall()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
