"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.stock_analysis_workflow_controller_api import StockAnalysisWorkflowControllerApi  # noqa: E501


class TestStockAnalysisWorkflowControllerApi(unittest.TestCase):
    """StockAnalysisWorkflowControllerApi unit test stubs"""

    def setUp(self):
        self.api = StockAnalysisWorkflowControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        """
        pass

    def test_evaluate(self):
        """Test case for evaluate

        """
        pass

    def test_refresh(self):
        """Test case for refresh

        """
        pass


if __name__ == '__main__':
    unittest.main()
