"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.comments_controller_api import CommentsControllerApi  # noqa: E501


class TestCommentsControllerApi(unittest.TestCase):
    """CommentsControllerApi unit test stubs"""

    def setUp(self):
        self.api = CommentsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_comments(self):
        """Test case for get_comments

        """
        pass

    def test_post_comment(self):
        """Test case for post_comment

        """
        pass


if __name__ == '__main__':
    unittest.main()
