"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item import Item
from openapi_client.model.waterfall import Waterfall
globals()['Item'] = Item
globals()['Waterfall'] = Waterfall
from openapi_client.model.derived_stock_analytics import DerivedStockAnalytics


class TestDerivedStockAnalytics(unittest.TestCase):
    """DerivedStockAnalytics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDerivedStockAnalytics(self):
        """Test DerivedStockAnalytics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DerivedStockAnalytics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
