"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fact_base_unsecured_controller_api import FactBaseUnsecuredControllerApi  # noqa: E501


class TestFactBaseUnsecuredControllerApi(unittest.TestCase):
    """FactBaseUnsecuredControllerApi unit test stubs"""

    def setUp(self):
        self.api = FactBaseUnsecuredControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_annual_time_series(self):
        """Test case for get_annual_time_series

        """
        pass

    def test_get_annual_time_series1(self):
        """Test case for get_annual_time_series1

        """
        pass

    def test_get_fact(self):
        """Test case for get_fact

        """
        pass


if __name__ == '__main__':
    unittest.main()
