"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.model import Model
globals()['Model'] = Model
from openapi_client.model.evaluate_model_request import EvaluateModelRequest


class TestEvaluateModelRequest(unittest.TestCase):
    """EvaluateModelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluateModelRequest(self):
        """Test EvaluateModelRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EvaluateModelRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
