"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.stock_analysis_projection import StockAnalysisProjection


class TestStockAnalysisProjection(unittest.TestCase):
    """StockAnalysisProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStockAnalysisProjection(self):
        """Test StockAnalysisProjection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StockAnalysisProjection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
