"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.edgar_entity_source import EdgarEntitySource


class TestEdgarEntitySource(unittest.TestCase):
    """EdgarEntitySource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgarEntitySource(self):
        """Test EdgarEntitySource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgarEntitySource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
