"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.xbrl_explicit_member import XbrlExplicitMember
globals()['XbrlExplicitMember'] = XbrlExplicitMember
from openapi_client.model.fact import Fact


class TestFact(unittest.TestCase):
    """Fact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFact(self):
        """Test Fact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
