"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.edgar_entity_source import EdgarEntitySource
globals()['EdgarEntitySource'] = EdgarEntitySource
from openapi_client.model.edgar_entity import EdgarEntity


class TestEdgarEntity(unittest.TestCase):
    """EdgarEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgarEntity(self):
        """Test EdgarEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgarEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
