"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.stock_analysis_controller_api import StockAnalysisControllerApi  # noqa: E501


class TestStockAnalysisControllerApi(unittest.TestCase):
    """StockAnalysisControllerApi unit test stubs"""

    def setUp(self):
        self.api = StockAnalysisControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_stock_analysis(self):
        """Test case for delete_stock_analysis

        """
        pass

    def test_find_stock_analyses(self):
        """Test case for find_stock_analyses

        """
        pass

    def test_get_stock_analysis(self):
        """Test case for get_stock_analysis

        """
        pass

    def test_publish(self):
        """Test case for publish

        """
        pass

    def test_save_stock_analysis(self):
        """Test case for save_stock_analysis

        """
        pass

    def test_unpublish(self):
        """Test case for unpublish

        """
        pass


if __name__ == '__main__':
    unittest.main()
