"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.stock_analysis_excel_downloader_controller_api import StockAnalysisExcelDownloaderControllerApi  # noqa: E501


class TestStockAnalysisExcelDownloaderControllerApi(unittest.TestCase):
    """StockAnalysisExcelDownloaderControllerApi unit test stubs"""

    def setUp(self):
        self.api = StockAnalysisExcelDownloaderControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download(self):
        """Test case for download

        """
        pass


if __name__ == '__main__':
    unittest.main()
