"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.model_template import ModelTemplate


class TestModelTemplate(unittest.TestCase):
    """ModelTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelTemplate(self):
        """Test ModelTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
