"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.issues_controller_api import IssuesControllerApi  # noqa: E501


class TestIssuesControllerApi(unittest.TestCase):
    """IssuesControllerApi unit test stubs"""

    def setUp(self):
        self.api = IssuesControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_issue(self):
        """Test case for delete_issue

        """
        pass

    def test_find_issues(self):
        """Test case for find_issues

        """
        pass

    def test_generate_issues(self):
        """Test case for generate_issues

        """
        pass

    def test_save_issues(self):
        """Test case for save_issues

        """
        pass


if __name__ == '__main__':
    unittest.main()
