"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cell import Cell
from openapi_client.model.derived_stock_analytics import DerivedStockAnalytics
globals()['Cell'] = Cell
globals()['DerivedStockAnalytics'] = DerivedStockAnalytics
from openapi_client.model.evaluate_model_response import EvaluateModelResponse


class TestEvaluateModelResponse(unittest.TestCase):
    """EvaluateModelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluateModelResponse(self):
        """Test EvaluateModelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EvaluateModelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
