"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.model import Model
from openapi_client.model.revenue_model import RevenueModel
globals()['Model'] = Model
globals()['RevenueModel'] = RevenueModel
from openapi_client.model.model_revenue_request import ModelRevenueRequest


class TestModelRevenueRequest(unittest.TestCase):
    """ModelRevenueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelRevenueRequest(self):
        """Test ModelRevenueRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelRevenueRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
