"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.stock_analysis2 import StockAnalysis2
globals()['StockAnalysis2'] = StockAnalysis2
from openapi_client.model.find_stock_analysis_response import FindStockAnalysisResponse


class TestFindStockAnalysisResponse(unittest.TestCase):
    """FindStockAnalysisResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindStockAnalysisResponse(self):
        """Test FindStockAnalysisResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FindStockAnalysisResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
