"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.fixed_cost_auto_fill import FixedCostAutoFill
from openapi_client.model.model import Model
from openapi_client.model.percent_of_another_item_auto_fill import PercentOfAnotherItemAutoFill
from openapi_client.model.percent_of_revenue_auto_fill import PercentOfRevenueAutoFill


class FactAutoFillerControllerApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __get_fixed_cost_auto_fills(
            self,
            fact_id,
            model,
            **kwargs
        ):
            """get_fixed_cost_auto_fills  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_fixed_cost_auto_fills(fact_id, model, async_req=True)
            >>> result = thread.get()

            Args:
                fact_id (str):
                model (Model):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [FixedCostAutoFill]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['fact_id'] = \
                fact_id
            kwargs['model'] = \
                model
            return self.call_with_http_info(**kwargs)

        self.get_fixed_cost_auto_fills = _Endpoint(
            settings={
                'response_type': ([FixedCostAutoFill],),
                'auth': [],
                'endpoint_path': '/api/fact-auto-filler/{factId}/fixed-cost',
                'operation_id': 'get_fixed_cost_auto_fills',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'fact_id',
                    'model',
                ],
                'required': [
                    'fact_id',
                    'model',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'fact_id':
                        (str,),
                    'model':
                        (Model,),
                },
                'attribute_map': {
                    'fact_id': 'factId',
                },
                'location_map': {
                    'fact_id': 'path',
                    'model': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__get_fixed_cost_auto_fills
        )

        def __get_percent_of_items_auto_fills(
            self,
            item_name,
            dependent_item_name,
            model,
            **kwargs
        ):
            """get_percent_of_items_auto_fills  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_percent_of_items_auto_fills(item_name, dependent_item_name, model, async_req=True)
            >>> result = thread.get()

            Args:
                item_name (str):
                dependent_item_name (str):
                model (Model):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [PercentOfAnotherItemAutoFill]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['item_name'] = \
                item_name
            kwargs['dependent_item_name'] = \
                dependent_item_name
            kwargs['model'] = \
                model
            return self.call_with_http_info(**kwargs)

        self.get_percent_of_items_auto_fills = _Endpoint(
            settings={
                'response_type': ([PercentOfAnotherItemAutoFill],),
                'auth': [],
                'endpoint_path': '/api/fact-auto-filler/{itemName}/percent-of-another-item',
                'operation_id': 'get_percent_of_items_auto_fills',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'item_name',
                    'dependent_item_name',
                    'model',
                ],
                'required': [
                    'item_name',
                    'dependent_item_name',
                    'model',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'item_name':
                        (str,),
                    'dependent_item_name':
                        (str,),
                    'model':
                        (Model,),
                },
                'attribute_map': {
                    'item_name': 'itemName',
                    'dependent_item_name': 'dependentItemName',
                },
                'location_map': {
                    'item_name': 'path',
                    'dependent_item_name': 'query',
                    'model': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__get_percent_of_items_auto_fills
        )

        def __get_percent_of_revenue_auto_fills(
            self,
            item_name,
            model,
            **kwargs
        ):
            """get_percent_of_revenue_auto_fills  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_percent_of_revenue_auto_fills(item_name, model, async_req=True)
            >>> result = thread.get()

            Args:
                item_name (str):
                model (Model):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [PercentOfRevenueAutoFill]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['item_name'] = \
                item_name
            kwargs['model'] = \
                model
            return self.call_with_http_info(**kwargs)

        self.get_percent_of_revenue_auto_fills = _Endpoint(
            settings={
                'response_type': ([PercentOfRevenueAutoFill],),
                'auth': [],
                'endpoint_path': '/api/fact-auto-filler/{itemName}/percent-of-revenue',
                'operation_id': 'get_percent_of_revenue_auto_fills',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'item_name',
                    'model',
                ],
                'required': [
                    'item_name',
                    'model',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'item_name':
                        (str,),
                    'model':
                        (Model,),
                },
                'attribute_map': {
                    'item_name': 'itemName',
                },
                'location_map': {
                    'item_name': 'path',
                    'model': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__get_percent_of_revenue_auto_fills
        )
